bracketSpacing: true
arrowParens: "always"
printWidth: 120
semi: false
singleQuote: true
tabWidth: 4
trailingComma: "all"

overrides:
  - files:
      - "*.json"
      - "*.yaml"
      - "*.yml"
    options:
      tabWidth: 2
